### ISSUE TITLE
no IE 8 support

### ISSUE THREAD

**Issue by 0101adm** [jwstadler/angular-jquery-dialog-service#7]
changed jquery library to 1.11.0.

"TypeError: Object doesn't support this property or method"

**Comment by jwstadler** [comment]
I updated and released v0.8.1. I added comments to the documentation and the example that highlight the need to use a jQuery 1.x release and also had to add a trim function to trim the templates since IE8 doesn't have a string.trim() method. That was the source of your error. If you find anything else, just let me know. Have a great Thanksgiving!
